name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    if: ${{ github.event.label.name == 'check' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Formatting Check
      run: |
        rustfmt --version
        cargo fmt
      
  clippy:
    if: ${{ github.event.label.name == 'check' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clippy Check
      run: cargo clippy -- -D warnings
        
  build:
    if: ${{ github.event.label.name == 'check' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run Tests
      run: cargo test --verbose
